import { Destination } from "../../src/types";

interface FallbackResult {
  headline: string;
  sub: string;
  destinations: Destination[];
}

export function getFallbackRecommendations(
  lokasi: string,
  mood: string[] = [],
  _preferensi: string[] = [],
  _budget: string = "standar"
): FallbackResult {
  const cleanLoc = lokasi.toLowerCase();

  let headline = `Kurasi Anti Wacana di ${lokasi}`;
  let sub = "Rekomendasi terbaik biar hari mager kamu jadi petualangan asyik!";

  if (cleanLoc.includes("menteng")) {
    headline = "Nongki Estetik ala Menteng Elite";
    sub = "Suasana teduh adem di tengah sibuknya Jakarta Pusat.";
  } else if (cleanLoc.includes("blok m") || cleanLoc.includes("melawai")) {
    headline = "Jelajah Pop-Culture di Blok M";
    sub = "Dari ruko bernuansa retro Jepang sampai ruang kreatif hits.";
  } else if (cleanLoc.includes("dago") || cleanLoc.includes("bandung")) {
    headline = "Wisata Sejuk khas Bandung Utara";
    sub = "Pariwisata adem berbukit buat kabur dari penat kerjaan.";
  }

  const listMenteng: Destination[] = [
    {
      name: "Taman Suropati",
      area: "Menteng, Jakarta Pusat",
      emoji: "🌳",
      distance: "5 menit",
      duration: "1-2 jam",
      price_range: "Gratis",
      price_num: 0,
      venue_type: "public",
      has_entrance_fee: false,
      payment_methods: "Tidak dipungut biaya",
      can_pay_digital: false,
      desc: "Tempat favorit buat melamun atau ngobrol santai di bawah pohon beringin rindang. Suasananya sejuk banget dengan musik dari pengamen biola jalanan.",
      tip: "Datang jam 4 sore pas udara mulai adem, cobain nasi gila legendaris di pinggir jalan sebelah taman.",
      tags: ["taman", "gratis", "outdoor"],
      mood_match: mood.includes("Santai / rebahan") ? ["Santai / rebahan"] : ["Santai / rebahan"],
    },
    {
      name: "Giyanti Coffee Roastery",
      area: "Surabaya, Menteng",
      emoji: "☕",
      distance: "8 menit",
      duration: "1-1.5 jam",
      price_range: "Rp 50-90rb",
      price_num: 65000,
      venue_type: "merchant",
      has_entrance_fee: false,
      payment_methods: "QRIS & Tunai",
      can_pay_digital: true,
      desc: "Cafe legendaris Menteng dengan interior vintage yang super estetik dan kebun outdoor mungil. Kopinya di-roast sendiri, bikin harum semerbak begitu kamu masuk.",
      tip: "Pesan Beef Pie-nya yang garing hangat sebagai temen ngopi, lalu cari spot duduk di halaman belakang biar dapet cahaya foto kece.",
      tags: ["kopi", "vintage", "konten"],
      mood_match: mood.includes("Lapar / haus") ? ["Lapar / haus"] : ["Konten / foto"],
    },
    {
      name: "Taman Menteng & Rumah Kaca",
      area: "Menteng, Jakarta Pusat",
      emoji: "🏛️",
      distance: "10 menit",
      duration: "45-60 mnt",
      price_range: "Gratis (parkir Rp 5rb)",
      price_num: 0,
      venue_type: "public",
      has_entrance_fee: false,
      payment_methods: "Tidak dipungut biaya masuk",
      can_pay_digital: false,
      desc: "Taman kota iconic dengan bangunan rumah kaca estetik di tengahnya. Sangat cocok buat jalan-jalan sore, foto ootd, atau nongki ringan bareng temen.",
      tip: "Naik ke jembatan penyeberangan dekat lapangan futsal buat foto dengan latar pencakar langit Jakarta.",
      tags: ["taman", "gratis", "foto"],
      mood_match: mood.includes("Konten / foto") ? ["Konten / foto"] : ["Santai / rebahan"],
    },
    {
      name: "Taman Situ Lembang",
      area: "Menteng, Jakarta Pusat",
      emoji: "🦆",
      distance: "6 menit",
      duration: "1 jam",
      price_range: "Gratis",
      price_num: 0,
      venue_type: "public",
      has_entrance_fee: false,
      payment_methods: "Tidak dipungut biaya masuk",
      can_pay_digital: false,
      desc: "Taman legendaris sejuk dengan danau berair tenang dan kawanan angsa liar yang gemas. Pilihan pas buat relaksasi mata setelah lelah bekerja seharian.",
      tip: "Duduk santai di bangku sebelah selatan menghadap danau untuk menikmati semburan air mancur dan hembusan angin sejuk.",
      tags: ["danau", "sejuk", "santai"],
      mood_match: ["Santai / rebahan"],
    },
    {
      name: "Shophaus Menteng",
      area: "Cikajang, Menteng",
      emoji: "🛍️",
      distance: "12 menit",
      duration: "1-2 jam",
      price_range: "Rp 35-75rb",
      price_num: 50000,
      venue_type: "merchant",
      has_entrance_fee: false,
      payment_methods: "Kartu Debit/Kredit, QRIS & Tunai",
      can_pay_digital: true,
      desc: "Pusat gaya ritel minimalis berkonsep terbuka yang menyatukan kedai es krim, kopi trendi, salon kecantikan, dan butik. Desain bangunannya modern tropical estetik.",
      tip: "Cobain es krim Gelato Secrets rasa salted caramel di lantai satu, porsinya pas untuk nemenin nongki sore.",
      tags: ["kuliner", "aesthetic", "belanja"],
      mood_match: ["Konten / foto"],
    },
    {
      name: "Sate Kaki Lima H. Ngadimun",
      area: "Besar, Menteng",
      emoji: "🍢",
      distance: "7 menit",
      duration: "30-45 mnt",
      price_range: "Rp 20-35rb",
      price_num: 25000,
      venue_type: "street",
      has_entrance_fee: false,
      payment_methods: "Tunai",
      can_pay_digital: false,
      desc: "Warung sate ayam kaki lima legendaris di pojokan Menteng dengan bumbu kacang gurih melimpah. Sangat direkomendasikan buat makan kenyang minim budget.",
      tip: "Pesan sate kulit setengah porsi dicampur sate daging biar teksturnya makin mantap saat dikunyah.",
      tags: ["kuliner", "kaki lima", "merakyat"],
      mood_match: ["Lapar / haus"],
    },
  ];

  const listBlokM: Destination[] = [
    {
      name: "Claypot Popo",
      area: "Melawai, Blok M",
      emoji: "🍜",
      distance: "7 menit",
      duration: "45-60 mnt",
      price_range: "Rp 30-50rb",
      price_num: 40000,
      venue_type: "merchant",
      has_entrance_fee: false,
      payment_methods: "QRIS & Tunai",
      can_pay_digital: true,
      desc: "Sajian claypot hangat dengan vibe ruko jadul pecinan klasik yang sangat nyaman. Cocok banget buat kamu yang perutnya keroncongan tapi kepengen makan estetik.",
      tip: "Menu Claypot Siram Telur Mentah itu juara bertahan di sini, aduk pas masih panas biar kentalnya mantap.",
      tags: ["kuliner", "vintage", "murah"],
      mood_match: ["Lapar / haus"],
    },
    {
      name: "Taman Literasi Martha Christina Tiahahu",
      area: "Trunojoyo, Blok M",
      emoji: "📖",
      distance: "4 menit",
      duration: "1-2 jam",
      price_range: "Gratis",
      price_num: 0,
      venue_type: "public",
      has_entrance_fee: false,
      payment_methods: "Tidak dipungut biaya masuk",
      can_pay_digital: false,
      desc: "Pusat baca dan berkumpul terbuka hijau di tengah Blok M yang baru direvitalisasi. Ada perpustakaan ber-AC, area duduk berundak, dan cafe mungil kekinian.",
      tip: "Spot terbaik buat nugas ada di ruang baca bundar lantai dua, suasananya tenang dengan pemandangan MRT lewat pelan.",
      tags: ["taman", "membaca", "kerja"],
      mood_match: ["Santai / rebahan"],
    },
    {
      name: "Rowndivision & Row Coffee",
      area: "Blok M Plaza Area",
      emoji: "🧥",
      distance: "10 menit",
      duration: "1 jam",
      price_range: "Rp 35-70rb",
      price_num: 45000,
      venue_type: "merchant",
      has_entrance_fee: false,
      payment_methods: "QRIS, GoPay, OVO & Tunai",
      can_pay_digital: true,
      desc: "Butik baju lokal/thrift store berpadu dengan kedai kopi bernuansa retro modern jepang. Kamu bisa belanja kaos-kaos vintage mbois sambil jepret foto ootd.",
      tip: "Area tangga samping ruko punya pencahayaan neon malam yang kece banget buat diposting di feed Instagram.",
      tags: ["belanja", "konten", "kopi"],
      mood_match: ["Konten / foto"],
    },
    {
      name: "M Bloc Space",
      area: "Panglima Polim, Blok M",
      emoji: "🎸",
      distance: "3 menit",
      duration: "2-3 jam",
      price_range: "Rp 25-60rb",
      price_num: 40000,
      venue_type: "merchant",
      has_entrance_fee: false,
      payment_methods: "QRIS & Tunai",
      can_pay_digital: true,
      desc: "Kawasan kreatif hits anak muda Jakarta dari bekas kompleks perumahan Peruri. Sering jadi spot pameran seni, gigs musik lokal, dan dipenuhi outlet kuliner.",
      tip: "Jangan bawa kendaraan pribadi karena areanya car-free, parkir di Blok M Square terdekat.",
      tags: ["seni", "musik", "muda"],
      mood_match: ["Konten / foto"],
    },
    {
      name: "Kopi Toko Djawa Blok M",
      area: "Melawai, Blok M",
      emoji: "🍪",
      distance: "5 menit",
      duration: "1 jam",
      price_range: "Rp 20-35rb",
      price_num: 25000,
      venue_type: "merchant",
      has_entrance_fee: false,
      payment_methods: "QRIS & Tunai",
      can_pay_digital: true,
      desc: "Kedai kopi legendaris asal Bandung dengan rasa es kopi susu manis khas gula jawa asli. Vibe di dalamnya hangat dan bernostalgia ria.",
      tip: "Pesan segelas Kopi Awan dengan topping foam dingin lembut dan pasangkan dengan donat cokelat klasik.",
      tags: ["kopi", "vintage", "cemilan"],
      mood_match: ["Lapar / haus"],
    },
    {
      name: "Warung Kaki Lima Bubur Barito",
      area: "Gandaria, Blok M",
      emoji: "🥣",
      distance: "9 menit",
      duration: "30-45 mnt",
      price_range: "Rp 15-25rb",
      price_num: 20000,
      venue_type: "street",
      has_entrance_fee: false,
      payment_methods: "Tunai",
      can_pay_digital: false,
      desc: "Bubur ayam kaki lima legendaris dengan taburan cheese stick garing kriuk di atasnya. Kebalikan dari bubur encer biasa, bubur di sini tebal dan gurih parah.",
      tip: "Minta tambahan telur ayam kampung mentah di dasar mangkuk panas biar makin creamy padat melimpah.",
      tags: ["kaki lima", "favorit", "malam"],
      mood_match: ["Lapar / haus"],
    },
  ];

  const listUmum: Destination[] = [
    {
      name: `Alun-Alun Kota ${lokasi}`,
      area: lokasi,
      emoji: "🪁",
      distance: "5 menit",
      duration: "1-2 jam",
      price_range: "Gratis",
      price_num: 0,
      venue_type: "public",
      has_entrance_fee: false,
      payment_methods: "Tidak dipungut biaya masuk",
      can_pay_digital: false,
      desc: `Pusat berkumpulnya warga lokal di sekitar ${lokasi} yang rindang dan ramah anggaran. Banyak penjual jajanan tradisional hangat dan mainan anak yang seru.`,
      tip: "Beli cilok bumbu kacang atau es dawet dari gerobak biru di sisi timur, rasanya otentik anti-gagal.",
      tags: ["lokal", "santai", "gratis"],
      mood_match: ["Santai / rebahan"],
    },
    {
      name: `Kopi Klasik Resto ${lokasi}`,
      area: lokasi,
      emoji: "☕",
      distance: "12 menit",
      duration: "1-2 jam",
      price_range: "Rp 25-50rb",
      price_num: 35000,
      venue_type: "merchant",
      has_entrance_fee: false,
      payment_methods: "QRIS & Tunai",
      can_pay_digital: true,
      desc: `Tempat nongkrong semi-outdoor berinterior hangat di ${lokasi} yang pas buat melepaskan penat. Menu kopi susu gula aren-nya sangat pas buat lidah lokal kamu.`,
      tip: "Cari kursi kayu yang nempel tembok luar biar ga kehalang tiang dan dapet sinyal wifi paling kencang.",
      tags: ["kopi", "pewe", "cemilan"],
      mood_match: ["Lapar / haus"],
    },
    {
      name: "Teras Sore Pandangan Indah",
      area: `${lokasi} Pinggiran`,
      emoji: "🌇",
      distance: "18 menit",
      duration: "1 jam",
      price_range: "Rp 15-30rb",
      price_num: 20000,
      venue_type: "merchant",
      has_entrance_fee: false,
      payment_methods: "QRIS & Tunai",
      can_pay_digital: true,
      desc: "Spot nongki bukit atau atap tersembunyi dengan pemandangan matahari terbenam yang mengagumkan. Cocok banget buat menutup hari santaimu bareng sobat dekat.",
      tip: "Sedia jaket tipis karena angin sore daerah sini lumayan kencang bertiup menjelang malam.",
      tags: ["senja", "romantis", "outdoor"],
      mood_match: ["Konten / foto"],
    },
    {
      name: "Hutan Kota Hijau Lestari",
      area: lokasi,
      emoji: "🌳",
      distance: "15 menit",
      duration: "1-2 jam",
      price_range: "Gratis",
      price_num: 0,
      venue_type: "public",
      has_entrance_fee: false,
      payment_methods: "Tidak dipungut biaya masuk",
      can_pay_digital: false,
      desc: "Hutan lindung mini yang asri dan sejuk di tengah area pemukiman padat kota ini. Udaranya segar bebas polusi dan cocok untuk mengistirahatkan pikiran.",
      tip: "Jangan lupa membawa lotion anti nyamuk sebelum masuk ke jalur pejalan kaki berkayu di dalam hutan.",
      tags: ["sejuk", "hutan", "gratis"],
      mood_match: ["Santai / rebahan"],
    },
    {
      name: "Pujasera Kuliner Malam Nusantara",
      area: `${lokasi} Sentra Kuliner`,
      emoji: "🍢",
      distance: "8 menit",
      duration: "1-1.5 jam",
      price_range: "Rp 15-40rb",
      price_num: 25000,
      venue_type: "street",
      has_entrance_fee: false,
      payment_methods: "Sebagian besar Tunai, beberapa lapak ada QRIS",
      can_pay_digital: true,
      desc: "Sentra jajanan kaki lima hits malam hari dengan beraneka sate madura, martabak manis hangat, dan sup buah segar pembakar selera.",
      tip: "Coba pesan roti bakar keju susu di gerobak bagian tengah, porsi serbuan kejunya melimpah ruah.",
      tags: ["kuliner", "jajanan", "malam"],
      mood_match: ["Lapar / haus"],
    },
    {
      name: `Kaki Lima Bakso Legendaris ${lokasi}`,
      area: lokasi,
      emoji: "🍜",
      distance: "6 menit",
      duration: "30-50 mnt",
      price_range: "Rp 15-25rb",
      price_num: 18000,
      venue_type: "street",
      has_entrance_fee: false,
      payment_methods: "Tunai",
      can_pay_digital: false,
      desc: "Rekomendasi bakso halus kaki lima urat jumbo legendaris yang murah meriah dan super kenyal. Kaldu kuah sapinya gurih nan bening alami.",
      tip: "Racik kuahnya sendiri dengan satu sendok penuh sambal merah ulek murni dan perasan jeruk limau segar.",
      tags: ["bakso", "kaki lima", "pedas"],
      mood_match: ["Lapar / haus"],
    },
  ];

  const destinations =
    cleanLoc.includes("menteng")
      ? listMenteng
      : cleanLoc.includes("blok m") || cleanLoc.includes("melawai")
      ? listBlokM
      : listUmum;

  return { headline, sub, destinations };
}
